### ISSUE TITLE
Curio issues

### ISSUE THREAD

**Issue by Alwinfy** [williewillus/botania-fabric-issues#23]
Tested on the beta snapshot posted on 11-25-2020
Update 02-05-2021: Tested a subset, everything I tested has been marked as working. Further tests required to confirm the rest

- [x] No curios render at all
- [x] Flügel Tiara gliding doesn't work, timer doesn't count down
- [x] Sashes give way too much jump boost (Soujourner's gives 5.5 blocks height, Globetrotter's gives 9.5)
- [ ] The following don't do anything:
- * [ ] Snow pendant
- * [x] Pyroclast pendant
- * [x] Tainted Blood pendants
- * [ ] Tiny Planet charm
- * [x] Invis cloak
- * [ ] The Spectator
- * [ ] Third Eye
- * [ ] Diva charm
- * [x] Far Reach ring
- * [x] Magnet ring
- * [ ] Swimming ring
- * [x] Jump pendants
- [x] Crimson pendant/Odin ring still displays fire after leaving e.g. lava
- [x] Magnet rings don't pull when active; after throwing an item they never reactivate
- [ ] Cloaks of Judgement don't have any cooldowns between triggers
- [ ] When placing with the Loki Ring, blocks are placed at every location _except_ the clicked one
- [x] Odin Ring doesn't give +20HP

**Comment by TheIllusiveC4** [comment]
I'm not sure if I should outline this in its own thread, but this is directly related so I'll just comment here.

Botania is attempting to register the Curios components [here](https://github.com/Vazkii/Botania/blob/7e4a4122e7b743e556626eecd9602b8fb85d2b5f/src/main/java/vazkii/botania/common/item/equipment/bauble/ItemBauble.java#L55) in the item constructor. However, that call does nothing if the `EquipmentHandler` instance [is null](https://github.com/Vazkii/Botania/blob/7e4a4122e7b743e556626eecd9602b8fb85d2b5f/src/main/java/vazkii/botania/common/core/handler/EquipmentHandler.java#L59) which is always true because the items are constructed and registered before the `EquipmentHandler` initialization done [here](https://github.com/Vazkii/Botania/blob/7e4a4122e7b743e556626eecd9602b8fb85d2b5f/src/main/java/vazkii/botania/common/Botania.java#L143) and no further attempts are made to register the components. This means that no Curios functionality can be present since the components were not actually registered.

Refactoring the logic so that the component registration is done after the `EquipmentHandler` initialization should address many of the issues outlined above, particularly regarding any rendering or ticking/equipping/attribute behavior.

**Comment by Alwinfy** [comment]
More were tested on the game-night server but in particular the Cloak issue is still confirmed present

**Comment by Hubry** [comment]
I think I found the cause for the cloak.

The callsite in a mixin:
https://github.com/Vazkii/Botania/blob/61ed36e47ae052d8af2d81a995548f3ce912b60f/src/main/java/vazkii/botania/mixin/MixinPlayerEntity.java#L113-L114

The method that checks cooldown:
https://github.com/Vazkii/Botania/blob/61ed36e47ae052d8af2d81a995548f3ce912b60f/src/main/java/vazkii/botania/common/item/equipment/bauble/ItemHolyCloak.java#L52-L58

The method that should be called through the method above and not directly:
https://github.com/Vazkii/Botania/blob/61ed36e47ae052d8af2d81a995548f3ce912b60f/src/main/java/vazkii/botania/common/item/equipment/bauble/ItemHolyCloak.java#L101-L103

(smh github, why no embeds for the code lines here)
It really seems like a cursory glance at the code (and paying attention to the IDE saying `onPlayerDamage` is unused) would have solved it :P
Too bad I am not really motivated to do much work with the port in my current state.

**Comment by williewillus** [comment]
@Alwinfy can you update/retest the ticket with the latest 1.17 build and remove everything that's been solved?

**Comment by MoriyaShiine** [comment]
This is probably safe to close? I'm going to be testing every trinket individually and will report any issues that show up

**Comment by williewillus** [comment]
sure
